### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by Yatekii** [ARMmbed/cmsis-pack-manager#127]
Hi!

Any chance this is making it to crates.io with proper docs soon?

Best,
Yatekii

**Comment by theotherjimmy** [comment]
Sure! What crates do you need published?

**Comment by Yatekii** [comment]
I think the correct answer here for me is all of them :P

I am writing https://github.com/probe-rs/probe-rs and I want to extract the flash blob from the CMSIS pack. Maybe you could quickly elaborate if that's even possible.
Because in all honesty I didn't find much code which does this and I didn't fully see through what this collection of crates actually does =)

**Comment by theotherjimmy** [comment]
@Yatekii That's very possible. I think pyOCD can do it with the python wrapper of these packages. I'll release the 0.1.0 with modified crate names. Checking for collisions right now.

**Comment by Yatekii** [comment]
Great! Looking forward to it! If you could point me to the relevant bits once its out, that would be great :)

**Comment by theotherjimmy** [comment]
Yeah, I'll post links in this issue as I publish the crates.

**Comment by Yatekii** [comment]
Sorry to bug, but do you have an ETA on this? :)

**Comment by theotherjimmy** [comment]
I don't. Thanks for reminding me to do this

**Comment by mathias-arm** [comment]
Crate is now published at https://crates.io/crates/cmsis-pack let me know if there is an issue.
