### ISSUE TITLE
Unifying the crates

### ISSUE THREAD

**Issue by Yatekii** [ARMmbed/cmsis-pack-manager#130]
Hi!

I just had a closer look at this lib. Is there a specific you made 8 small crates instead of a big one?
I think it's highly preferrable to have one single crate since all of this functionality is tightly coupled.

What do you think about this?

Best,
Yatekii

**Comment by theotherjimmy** [comment]
@Yatekii I started this project before incremental compile was enabled on nightly. I'd be happy to unify most of the crates, excluding cmsis-cffi and cmsis-cli, as I don't expect users of the Rust crates to care about a foreign function interface, or an incomplete CLI.

**Comment by Yatekii** [comment]
Sounds great! Should I make a PR or do you do it yourself?

**Comment by theotherjimmy** [comment]
@Yatekii I don't currently have much time allocated to cmsis-pack-manager. I would appreciate a PR if you have the time.
