### ISSUE TITLE
feature-request: add a get function to algorithm by name

### ISSUE THREAD

**Issue by orenc17A** [ARMmbed/cmsis-pack-manager#36]
most of the time iterating over the algorithms isn't useful

**Comment by theotherjimmy** [comment]
The algorithms have a file name. were you referring to that? That really begs the question: if you already have the file name, why do you even need to look up the algorithm.

I was expecting that a user would have a region of flash and go looking for compatible algorithms.

**Comment by theotherjimmy** [comment]
I think what you're looking for is:
```python
c = Cache(True, True)
c.pack_from_cache(device).open(algo_file)
```
