### ISSUE TITLE
Add device family vendor to index

### ISSUE THREAD

**Issue by flit** [ARMmbed/cmsis-pack-manager#73]
I need the device vendor from the `family` element in the PDSC available in the dictionary returned by `Cache.index`.

**Comment by theotherjimmy** [comment]
@flit are you referring to `Dvendor` http://www.keil.com/pack/doc/CMSIS/Pack/html/pdsc_family_pg.html#element_family ? It should already be present for each device in 0.2.3.

**Comment by flit** [comment]
Ah, you're right! Either I just missed it or was looking at an old version. Thanks.
