### ISSUE TITLE
JSON index files are always rebuilt

### ISSUE THREAD

**Issue by flit** [ARMmbed/cmsis-pack-manager#99]
It seems that CPM always rebuilds the JSON index files from the .pdsc files, even if only downloading a pack already referenced in the index. This takes a considerable amount of time, on the order of 15 seconds on a very fast MacBook Pro. Actually downloading the pack is usually much faster than that.

The index should only be rebuilt when the PDSC files are downloaded.

**Comment by theotherjimmy** [comment]
Agreed. What's really interesting is that it's almost not noticeable on my linux boxes because rebuilding the JSON takes so little time.
